engine:
  name: tofu
  version: "1.12.5"

hooks:
  all:
    pre_init:
      - type: env
        name: AWS_ACCESS_KEY_ID
        value: "test"
      - type: env
        name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - type: env
        name: AWS_DEFAULT_REGION
        value: "ap-south-1"
      - type: env
        name: AWS_EC2_METADATA_DISABLED
        value: "true"
