engine:
  name: tofu
  version: "1.12.5"

hooks:
  plan:
    pre:
      - type: env
        name: AWS_ACCESS_KEY_ID
        cmd: ['echo', 'test']
      - type: env
        name: AWS_SECRET_ACCESS_KEY
        cmd: ['echo', 'test']
      - type: env
        name: AWS_DEFAULT_REGION
        cmd: ['echo', 'ap-south-1']
      - type: env
        name: AWS_EC2_METADATA_DISABLED
        cmd: ['echo', 'true']
  apply:
    pre:
      - type: env
        name: AWS_ACCESS_KEY_ID
        cmd: ['echo', 'test']
      - type: env
        name: AWS_SECRET_ACCESS_KEY
        cmd: ['echo', 'test']
      - type: env
        name: AWS_DEFAULT_REGION
        cmd: ['echo', 'ap-south-1']
      - type: env
        name: AWS_EC2_METADATA_DISABLED
        cmd: ['echo', 'true']
