##########################################################################
# See https://terrateam.io/docs
##########################################################################
name: 'Terrateam Workflow'
on:
  workflow_dispatch:
    inputs:
      # work-token and api-base-url are automatically passed in by the Terrateam backend
      work-token:
        description: 'Work Token'
        required: true
      api-base-url:
        description: 'API Base URL'
      environment:
        description: 'Environment in which to run the action'
        type: environment
      runs_on:
        description: 'runs-on configuration'
        type: string
        default: '"ubuntu-latest"'
jobs:
  terrateam:
    permissions:
      id-token: write
      contents: read
    # runs-on: ${{ fromJSON(github.event.inputs.runs_on) }}
    timeout-minutes: 10
    name: Terrateam Action
    environment: '${{ github.event.inputs.environment }}'
    runs-on: infra
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Kubernetes credentials
        run: |
          mkdir -p "$GITHUB_WORKSPACE/.k8s-sa"
          cp -L /var/run/secrets/kubernetes.io/serviceaccount/token "$GITHUB_WORKSPACE/.k8s-sa/token"
          cp -L /var/run/secrets/kubernetes.io/serviceaccount/ca.crt "$GITHUB_WORKSPACE/.k8s-sa/ca.crt"
          
      - name: Run Terrateam Action
        id: terrateam
        uses: terrateamio/action@v1
        timeout-minutes: 5
        with:
          work-token: '${{ github.event.inputs.work-token }}'
          api-base-url: '${{ github.event.inputs.api-base-url }}'
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
